ja.MyAppName=Firebirdデータベースサーバー %1
ja.ServerInstall=サーバーと開発ツールの完全なインストール。
ja.SuperServerInstall=スーパーサーバーと開発ツールのフルインストール。
ja.ClassicServerInstall=クラシックサーバーと開発ツールの完全インストール。
ja.DeveloperInstall=開発者およびデータベース管理者向けのクライアント ツールのインストール。
ja.ClientInstall=最小限のクライアント インストール - サーバーもツールも必要ありません。
ja.CustomInstall=カスタムインストール
ja.SuperServerComponent=スーパーサーバーバイナリ
ja.ClassicServerComponent=クラシックサーバーバイナリ
ja.ServerComponent=サーバーコンポーネント
ja.DevAdminComponent=開発者および管理ツールのコンポーネント
ja.ClientComponent=クライアントコンポーネント
ja.UseGuardianTask=サーバー制御に &Guardian を使用しますか？
ja.UseApplicationTaskMsg=&Application として実行しますか？
ja.TaskGroupDescription=Firebirdサーバーを次で実行する:
ja.UseServiceTask=&Service として実行しますか？
ja.AutoStartTask=起動時に毎回 &Firebird を自動的に実行しますか？
ja.SuperClassicTask=スーパークラシックを使用しますか？
ja.CopyFbClientToSysTask=Firebirdの クライアント ライブラリをシステムディレクトリにコピーしますか？
ja.CopyFbClientAsGds32Task=レガシー なInterBaseのサポートのために、GDS32.DLL クライアントライブラリを生成しますか？
ja.InstallCPLAppletTask=コントロール パネル アプレットをインストールしますか？
ja.instreg=レジストリをアップデート中
ja.instclientCopyFbClient=fbclient を <sys> ディレクトリにコピー中
ja.instclientGenGds32= gds32.dllを <sys> ディレクトリに生成中
ja.instclientDecLibCountGds32=gds32 の共有ライブラリカウントを減らし、必要に応じて削除します。
ja.instclientDecLibCountFbClient=fbclient の共有ライブラリカウントを減らし、必要に応じて削除します。
ja.instsvcSetup=サービスをセットアップ中
ja.instsvcStartQuestion=Firebirdサービスを今すぐ起動しますか?
ja.instsvcStartMsg=サーバーを起動中
ja.instsvcStopMsg=サービスを停止中
ja.instsvcRemove=サービスを削除中
ja.instappStartQuestion=Firebirdを今すぐスタートしますか？
ja.instappStartMsg=サーバーを起動中

ja.InstallSummarySuffix1=このバージョンの Firebird はデフォルトのインストールになります。
ja.InstallSummarySuffix2=また、このバージョンの Firebird をインストールする際には注意してください。
ja.InstallSummarySuffix3=より新しいバージョンがすでにインストールされている場合、
ja.InstallSummarySuffix4=予測できない結果を引き起こす可能性があります。

ja.InstallSummaryCancel1=このインストールを続行すると、Firebird はインストールされますが、設定は行われません。
ja.InstallSummaryCancel2=インストールを手動で完了する必要があります。
ja.InstallSummaryCancel3=このインストールをキャンセルしますか？

ja.InstalledProducts=事前インストール分析により、%s の既存の Firebird または Interbase %s が検出されました。
ja.InstalledProdCountSingular=単一のバージョンが存在します
ja.InstalledProdCountPlural=複数のバージョンが存在します

ja.FbRunning1=既存の %s サーバーが実行中です。
ja.FbRunning2=続行する前に、アプリケーションを閉じるか、
ja.FbRunning3=サービスを停止する必要があります。

ja.PreviousInstallBroken=  （バージョン文字列の不一致により、インストールが破損しているように見えます。）
ja.PreviousInstallGood=   (インストールは正常です。)

ja.IconReadme=Firebird %1 Readme
ja.IconUninstall=Firebird %1 をアンインストールする
ja.ReleaseNotes= リリースノート。 (Acrobatリーダーが必要です。)
ja.InstallationGuide= インストールガイド。 (Acrobatリーダーが必要です。)
ja.BugFixes= バグフィックス。 (Acrobatリーダーが必要です。)
ja.Uninstall=Firebird %1 をアンインストールする
ja.Winsock2Web1=Winsock 2 がインストールされていません。
ja.Winsock2Web2=Winsock 2 アップデートのホームページを訪問しますか？
ja.NoWinsock2=続行する前に Winsock 2 のアップデートをインストールしてください
ja.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

ja.RunCSNoGuardian=Firebird クラシックサーバーを実行する (Guardian無し)
ja.RunSSNoGuardian=Firebird スーパーサーバーを実行する (Guardian無し)
ja.RunSSWithGuardian=Firebird スーパーサーバーを実行する (Guardian有り)
ja.RunCSWithGuardian=Firebird クラシックサーバーを実行する (Guardian有り)
ja.RunISQL=コマンドラインベースのインタラクティブ SQL tool（ISQL）を実行する

ja.ReadmeFile=readme.txt
ja.InstallationReadmeFile=installation_readme.txt
ja.IncompleteTranslationNotice=この文書は最新ではありません。最新の情報については、オリジナルの英語版を参照してください。
ja.RunCS=Firebird をクラシックサーバーモードで実行する
ja.RunSC=Firebird をスーパークラシックモードで実行する
ja.RunSS=Firebird をスーパーサーバーモードで実行する
ja.ServerTaskDescription=サーバーアーキテクチャを選択:
ja.initSecurityDb=SYSDBA をセキュリティデータベースに追加中。
ja.SYSDBAPasswordMismatch=入力されたパスワードが一致しません。SYSDBA パスワードを再入力してください。
ja.SYSDBAPasswordEmpty=パスワードが空欄です。SYSDBA パスワードは必ず入力してください。
ja.EnableLegacyClientAuth=レガシーな Firebird 用の 認証を有効にしますか？
ja.CreateSYSDBAPassword=データベースシステム管理者用のパスワードを作成する
ja.ClickThroughPWCreation=または、デフォルトのパスワード「masterkey」を使用するにはそのまま進んでください。
ja.PasswordNote=*** 注 - Firebird 3 では、masterkey と masterke は違うパスワードとして扱われます。 ***
ja.SYSDBAPassword=SYSDBA パスワード:
ja.RetypeSYSDBAPassword=SYSDBA パスワードを再入力:
ja.InstallingMSVC32runtimes=MSVC 32-bit ランタイムライブラリをシステムディレクトリにインストール中
ja.InstallingMSVC64runtimes=MSVC 64-bit ランタイムライブラリをシステムディレクトリにインストール中

