/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:3279
*/

#define PRODUCT_VER_STRING "4.0.8.3279"
#define FILE_VER_STRING "WI-V4.0.8.3279"
#define LICENSE_VER_STRING "WI-V4.0.8.3279"
#define FILE_VER_NUMBER 4, 0, 8, 3279
#define FB_MAJOR_VER "4"
#define FB_MINOR_VER "0"
#define FB_REV_NO "8"
#define FB_BUILD_NO "3279"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 4.0"
